kind: pipeline
type: docker
name: default

workspace:
  path: /drone/drone-plugin-tencent-cos

steps:
- name: build
  image: golang
  commands:
  - go build
  - go test ./...

- name: publish
  image: plugins/docker
  settings:
    repo: kitmi/drone-plugin-tencent-cos
    auto_tag: true
    dockerfile: docker/Dockerfile
    username: kitmi
    password:
      from_secret: docker_password

trigger:
  branch:
    - main
  event:
    - push
    - pull_request
